### PR TITLE
Remove PyTorch Lightning dependency

### PR DESCRIPTION
**Pull request by MilesCranmer**
- Removes the PyTorch Lightning dependency which was too heavyweight
  - (Ideally we could also remove the Torch dependency, but seems like a bit more work)
- Switches from pickle to [safetensors](https://github.com/huggingface/safetensors) which is a faster and safer way to store model weights
  - Also I upload the file used to do this translation, for posterity (in case had fine-tuned a custom model)
- Stores model hyperparameters in accompanying json files

Also I made the README example of deep regressor a bit better.

### CODE REVIEW

**Comment by dtamayo** [comment]
Awesome...we were also running into trouble with pickled model files with Caleb. Pytorch seemed to suggest this to avoid pickling:

https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference

Safetensors is more robust?

**Comment by MilesCranmer** [comment]
Yeah safetensors is pretty much all that they recommend there, plus additional stuff to make it even safer (since pickle allows arbitrary code execution).

Also don't merge this yet; trying to fix some issues...

**Comment by dtamayo** [comment]
If you figure it out, could you tell Caleb how you did it so we can save his models your way? With pickle it also causes problems being loaded in a different module from the one in which it was saved.

**Comment by MilesCranmer** [comment]
What is his branch?

**Comment by dtamayo** [comment]
working on the caleb branch

**Comment by MilesCranmer** [comment]
Thanks!

Okay I think this PR is ready for review. I also removed the pandas and matplotlib dependency for good measure.

**Comment by MilesCranmer** [comment]
Re: Caleb's branch, I don't see data for the model stored anywhere (?)

**Comment by dtamayo** [comment]
Thanks so much Miles. Will merge these changes into the caleb branch and add a test

**Pull request merged**
